// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa-aQpN97JJehXY5mWlU6xosENJgvdoiQ',
    appId: '1:716425661652:web:32161e3da65cee9036ff41',
    messagingSenderId: '716425661652',
    projectId: 'fitraho-flutterfledgings',
    authDomain: 'fitraho-flutterfledgings.firebaseapp.com',
    storageBucket: 'fitraho-flutterfledgings.appspot.com',
    measurementId: 'G-YW4QFWCF6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY1-wmoDmfGsUDf66xSlTvzPVt8CXtjrQ',
    appId: '1:716425661652:android:7ebf8ea203bd186f36ff41',
    messagingSenderId: '716425661652',
    projectId: 'fitraho-flutterfledgings',
    storageBucket: 'fitraho-flutterfledgings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-qb5QaqwuluyrocJQdV_moSdLWqv7zvc',
    appId: '1:716425661652:ios:25c56bf5ed353ef636ff41',
    messagingSenderId: '716425661652',
    projectId: 'fitraho-flutterfledgings',
    storageBucket: 'fitraho-flutterfledgings.appspot.com',
    iosClientId: '716425661652-43vlq76o7hmop5oun0ftjq7mkb973nfa.apps.googleusercontent.com',
    iosBundleId: 'com.flutterfledgings.fitRaho',
  );
}
